//@version=6
indicator(title="VWAP + EMA9", shorttitle="VWAP+EMA9", overlay=true, timeframe="", timeframe_gaps=true)

// ==========================================
// Group inputs logically
// ==========================================

// VWAP Settings
vwap_group = "VWAP Settings"
hideonDWM = input(false, title="Hide VWAP on 1D or Above", group=vwap_group, display=display.data_window)
var anchor = input.string(defval="Session", title="Anchor Period",
 options=["Session", "Week", "Month", "Quarter", "Year", "Decade", "Century", "Earnings", "Dividends", "Splits"], group=vwap_group)
vwap_src = input(title="VWAP Source", defval=hlc3, group=vwap_group, display=display.data_window)
vwap_offset = input.int(0, title="VWAP Offset", group=vwap_group, minval=0, display=display.data_window)

// EMA Settings
ema_group = "EMA Settings"
ema_len = input.int(9, minval=1, title="EMA Length", group=ema_group)
ema_src = input(close, title="EMA Source", group=ema_group)
ema_offset = input.int(title="EMA Offset", defval=0, minval=-500, maxval=500, group=ema_group, display=display.data_window)
ema_color = input.color(color.blue, "EMA Color", group=ema_group)

// Smoothing MA inputs
smooth_group = "Smoothing Settings"
TT_BB = "Only applies when 'SMA + Bollinger Bands' is selected. Determines the distance between the SMA and the bands."
maTypeInput = input.string("None", "Smoothing Type", options=["None", "SMA", "SMA + Bollinger Bands", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group=smooth_group, display=display.data_window)
maLengthInput = input.int(14, "Smoothing Length", group=smooth_group, display=display.data_window)
bbMultInput = input.float(2.0, "BB StdDev", minval=0.001, maxval=50, step=0.5, tooltip=TT_BB, group=smooth_group, display=display.data_window)
smooth_color = input.color(color.yellow, "Smoothing MA Color", group=smooth_group)
bb_color = input.color(color.green, "Bollinger Bands Color", group=smooth_group)

// ==========================================
// VWAP Calculation
// ==========================================

cumVolume = ta.cum(volume)
if barstate.islast and cumVolume == 0
    runtime.error("No volume is provided by the data vendor.")

new_earnings = request.earnings(syminfo.tickerid, earnings.actual, barmerge.gaps_on, barmerge.lookahead_on, ignore_invalid_symbol=true)
new_dividends = request.dividends(syminfo.tickerid, dividends.gross, barmerge.gaps_on, barmerge.lookahead_on, ignore_invalid_symbol=true)
new_split = request.splits(syminfo.tickerid, splits.denominator, barmerge.gaps_on, barmerge.lookahead_on, ignore_invalid_symbol=true)

isNewPeriod = switch anchor
    "Earnings"  => not na(new_earnings)
    "Dividends" => not na(new_dividends)
    "Splits"    => not na(new_split)
    "Session"   => timeframe.change("D")
    "Week"      => timeframe.change("W")
    "Month"     => timeframe.change("M")
    "Quarter"   => timeframe.change("3M")
    "Year"      => timeframe.change("12M")
    "Decade"    => timeframe.change("12M") and year % 10 == 0
    "Century"   => timeframe.change("12M") and year % 100 == 0
    => false

isEsdAnchor = anchor == "Earnings" or anchor == "Dividends" or anchor == "Splits"
if na(vwap_src[1]) and not isEsdAnchor
    isNewPeriod := true

float vwapValue = na

if not (hideonDWM and timeframe.isdwm)
    [_vwap, _, _] = ta.vwap(vwap_src, isNewPeriod, 1)
    vwapValue := _vwap

// ==========================================
// EMA Calculation
// ==========================================

ema_value = ta.ema(ema_src, ema_len)

// ==========================================
// Smoothing MA Calculation
// ==========================================

var enableMA = maTypeInput != "None"
var isBB = maTypeInput == "SMA + Bollinger Bands"

ma(source, length, MAtype) =>
    switch MAtype
        "SMA"                   => ta.sma(source, length)
        "SMA + Bollinger Bands" => ta.sma(source, length)
        "EMA"                   => ta.ema(source, length)
        "SMMA (RMA)"            => ta.rma(source, length)
        "WMA"                   => ta.wma(source, length)
        "VWMA"                  => ta.vwma(source, length)

// Apply smoothing to EMA
smoothingMA = enableMA ? ma(ema_value, maLengthInput, maTypeInput) : na
smoothingStDev = isBB ? ta.stdev(ema_value, maLengthInput) * bbMultInput : na

// ==========================================
// Plotting
// ==========================================

// Plot VWAP
plot(vwapValue, title="VWAP", color=color.fuchsia, offset=vwap_offset)

// Plot EMA
plot(ema_value, title="EMA", color=ema_color, offset=ema_offset)

// Plot Smoothing MA and Bollinger Bands
plot(smoothingMA, "EMA-based MA", color=smooth_color, display=enableMA ? display.all : display.none, editable=enableMA)
bbUpperBand = plot(smoothingMA + smoothingStDev, title="Upper Bollinger Band", color=bb_color, display=isBB ? display.all : display.none, editable=isBB)
bbLowerBand = plot(smoothingMA - smoothingStDev, title="Lower Bollinger Band", color=bb_color, display=isBB ? display.all : display.none, editable=isBB)
fill(bbUpperBand, bbLowerBand, color=isBB ? color.new(bb_color, 90) : na, title="Bollinger Bands Background Fill", display=isBB ? display.all : display.none, editable=isBB)
